// <auto-generated />
namespace ContactPro.Migrations.App
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSpecInst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSpecInst));
        
        string IMigrationMetadata.Id
        {
            get { return "201902060310010_AddSpecInst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
